### ISSUE TITLE
Promise rejection warning

### ISSUE THREAD

**Issue by mreishere** [lightpohl/podcast-dl#10]
Hi,

I am getting the following error: with "https://feeds.megaphone.fm/richdad"

> (node:13184) UnhandledPromiseRejectionWarning: TypeError: Expected a string
>     at filenamify (C:\snapshot\podcast-dl\node_modules\filenamify\index.js:15:9)
>     at getSafeName (C:\snapshot\podcast-dl\bin\naming.js:8:10)
>     at getFolderName (C:\snapshot\podcast-dl\bin\naming.js:45:22)
>     at main (C:\snapshot\podcast-dl\bin\bin.js:108:5)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> (node:13184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:13184) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

It seems to work with other podcast programs, so not sure if I'm doing something wrong.
(apologies if I have submitted this wrong -first time submitting an issue on github)

Great program btw.

**Comment by lightpohl** [comment]
Hey! Sorry for the delay.

Sounds like the program might be having issues with the title of the podcast it tried to pull from that feed. I'll take a look at this evening and update this issue. 👍

**Comment by lightpohl** [comment]
Looks like that feed has a slightly non-standard spec (it's missing a top-level `link` tag) and revealed an issue with name template system. [I've just released v3.0.1](https://github.com/lightpohl/podcast-dl/releases/tag/v3.0.1) which will fix the issue with this feed.

Thanks for the bug report!
