### ISSUE TITLE
Error 406 - Logfile

### ISSUE THREAD

**Issue by quotengrote** [lightpohl/podcast-dl#13]
Hi, first of all, thanks for that little tool.

I have a feed (https://feeds.br.de/radiowissen/feed.xml) on which i get Error 406. Is there a way to log the error so i can look whats wrong with it?
The Feed works in other Clients.

Wishes
mg

PS:
Used command: `--url https://feeds.br.de/radiowissen/feed.xml --out-dir C:\Users\mg\Desktop\{{podcast_title}} --include-episode-meta --include-meta --episode-template "{{release_date}} - {{title}}"`

**Comment by lightpohl** [comment]
Hey again! I'll take a look at this when I'm back at computer in a couple days.

Might either be an issue with the server response or the request header the underlying RSS parsing library this project is using. 👍

**Comment by quotengrote** [comment]
Hi again,

thx, no hurry.

Wishes
mg

**Comment by lightpohl** [comment]
[Fixed in v4.0.1](https://github.com/lightpohl/podcast-dl/releases/tag/v4.0.1). The podcast server wasn't happy with the default `accept` header and wanted it specified. Easy fix.🤷‍♂️

Thanks for the bug report!

**Comment by quotengrote** [comment]
Thx, now al BR Podcasts work without Problems. :-)
