### ISSUE TITLE
feature: add templating support to `--archive` option

### ISSUE THREAD

**Issue by quotengrote** [lightpohl/podcast-dl#15]
Hi,

the Parameter "--archive" does not recognize the variable {{podcast_title}} in the path.

## Example
`--url https://sternengeschichten.podigee.io/feed/aac --out-dir Z:\Podcasts\{{podcast_title}} --include-episode-meta --include-meta --episode-template "{{release_date}} - {{title}}" --archive Z:\Podcasts\{{podcast_title}}\archive.log`

### Output
- a file name {{podcast_title}} is created in "Z:\Podcasts\"

thx
mg

**Comment by lightpohl** [comment]
Oh, interesting! I hadn't thought about someone wanting to use the templating for the archive location. I'll take a look at that soon! 👍

**Comment by lightpohl** [comment]
Hey! Thanks for the feature request. Basic templating for the `--archive` flag is [added in v4.1.0](https://github.com/lightpohl/podcast-dl/releases/tag/v4.1.0).
