### ISSUE TITLE
Off-by-one error with --reverse option

### ISSUE THREAD

**Issue by ahizzey** [lightpohl/podcast-dl#16]
Using the `--reverse` option will cause the most recent podcast to not be downloaded

i.e.
* Running `podcast-dl-linux-x64 --reverse` leads to all but the most recent podcast to be downlaoded
* Running `podcast-dl-linux-x64` without the `--reverse` option leads to all podcasts (correctly) being downloaded

**Comment by lightpohl** [comment]
Thanks for the bug report!

Been wanting to take a look at that logic—will post back once a fix is available. 👍

**Comment by lightpohl** [comment]
This is now fixed and [released in v4.1.1](https://github.com/lightpohl/podcast-dl/releases/tag/v4.1.1). Let me know if you run into any issues with it!
