### ISSUE TITLE
Feature Request: --download-archive option

### ISSUE THREAD

**Issue by garrettdowd** [lightpohl/podcast-dl#2]
Similar to the --download-archive option in [youtube-dl](https://github.com/ytdl-org/youtube-dl#video-selection), this option would 

1. log every file that is downloaded
2. prevent re-downloading the same files/epiodes by checking the log file

From youtube-dl this option is described as
`Download only videos not listed in the archive file. Record the IDs of all downloaded videos in it.`

This would enable users to schedule podcast-dl to run and hav it only download new files/episodes.

**Comment by lightpohl** [comment]
This is a great suggestion! I implemented something like this for [gb-dl](https://github.com/lightpohl/gb-dl#archive). Moving over some of that logic to here should be pretty straightforward.

**Comment by lightpohl** [comment]
Done! New `--archive` option [available in v1.4.0](https://github.com/lightpohl/podcast-dl/releases/tag/v1.4.0).

**Comment by garrettdowd** [comment]
Nice! So fast :D Will give it a try soon. This alone would make podcast-dl more useful than youtube-dl for podcast rss feeds.
