### ISSUE TITLE
Feature request: allow printing/exporting list of episodes in JSON format

### ISSUE THREAD

**Issue by manojkarthick** [lightpohl/podcast-dl#29]
Thanks again for creating this tool! Currently podcast-dl prints the list of episodes in a table format, but being able to print in JSON format would be really useful. 

For example, something like this:
```
--list                             # prints in table format
--list --format=table  # print in table format
--list --format=json   # print in JSON format
```

The scenarios where this might be potentially useful:

- saving the list of episodes as JSON metadata alongside podcast/episode metadata
- pass the output of the list option to a tool like jq and calculate offset/limit based on some logic (eg. time period) to download specific episodes

**Comment by lightpohl** [comment]
Great suggestion! Thanks for opening an issue.

I'll see if I can append the functionality to the existing flag, so the behavior would then be:
- `--list`: prints in table format
- `--list "table"`: prints in table format
- `--list "json"`: prints in JSON format

I'll get this into the next update. 👍

**Comment by lightpohl** [comment]
Thanks again!

[Added in v5.1.0](https://github.com/lightpohl/podcast-dl/releases/tag/v5.1.0) with the `--list-format` option. Checkout the README for more details. 👍

**Comment by manojkarthick** [comment]
Thanks you so much for adding this feature! Should be really helpful 👍
