### ISSUE TITLE
BUG: --archive saves file to wrong location when using --out-dir

### ISSUE THREAD

**Issue by garrettdowd** [lightpohl/podcast-dl#3]
--archive saves the archive log in the working directory and not in the location specified by --out-dir.

It would make sense to always store the log file along with the relevant files.

**Comment by lightpohl** [comment]
Hey! `--archive` takes a path like `--out-dir` so you can better control which archive you want to use. For example, I use the save archive file for multiple podcasts in a config folder.

But if you want to have it saved to the same `--out-dir`, you would just need to repeat yourself a bit like so: `npx podcast-dl --url <URL> --out-dir <OUT_DIR> --archive <OUT_DIR>/archive.json
