### ISSUE TITLE
[Feature request] Initalize archive.json without downloading all old episodes

### ISSUE THREAD

**Issue by bbo2adwuff** [lightpohl/podcast-dl#31]
I had this thought already before but I didn't find time to make a pull request.

If I want to start following a podcast that already has in my case 300+ episodes and I just want to listen to the new weekly episodes rather than downloading all the old ones.

I was thinking that something like `--archive-initalize` could be used to just run these lines without the actual download:

https://github.com/lightpohl/podcast-dl/blob/c24650665abf422d5e0d9ee7986e044280588387/bin/util.js#L417-L419

If you like this idea I can make a pull request in 2-3 weeks or so.

Plus I just thought maybe a default option for `--archive` could also be nice (i.e. using `basePath/archive.json`)?

**Comment by lightpohl** [comment]
Hey! I have a couple options I've wanted to add that wouldn't require updating the archive logic and would work for your use case:

- `--after`: specify a date that the podcast release date must be after to download.
- `--before`: specify a date that the podcast release date must be before to download.

You could then just specify the date you started listening in `--after` and it wouldn't clog up the archive file.

What do you think?

**Comment by lightpohl** [comment]
A default for the archive path makes sense to me! I'll get that added too.

**Comment by lightpohl** [comment]
Just added `--after` and `--before` in v5.4.0. Let me know if that works out for you! 🚀

**Comment by bbo2adwuff** [comment]
Nice :rocket: Great new features :smile: 
Just tested `--after` and it's working as expected! Thanks.

Sorry I didn't have time to check your commits yet, but how is the default for the archive path supposed to work? When I run `podcast-dl --archive --after 08/01/2021 --url ...` then there is an archive file created with the filename `./--after` and obviously the `--after` argument is ignored.

When I run `podcast-dl --url ... --archive` I get `error: option '--archive <path>' argument missing`.

**Comment by lightpohl** [comment]
@bbo2adwuff - Apologies, I had a misunderstanding about optional commander options. Fixed in the latest release: [v6.0.0](https://github.com/lightpohl/podcast-dl/releases/tag/v6.0.0).
