### ISSUE TITLE
Feature request: flag to replace existing files if not in archive

### ISSUE THREAD

**Issue by Eloquite** [lightpohl/podcast-dl#33]
If, while downloading a podcast, the server errors and the file isn't completely downloaded, Podcast-dl will move to the next file without logging the broken file in the archive.

If you then re-download the podcast to fetch new episodes, the existing broken file is skipped and logged in the archive as if it were a successful download, thereby leaving you with an incomplete file.

I think it would be useful if we could tell Podcast-dl to always replace existing files as long as they're not logged in the archive.

**Comment by lightpohl** [comment]
Hey @Eloquite — Thanks for opening up an issue! Just noting a couple things:

1. The script shouldn't be adding those bad downloads to the archive file but...
2. The script does skip over local file conflicts which I believe is what you're running into (let me know if `1` is incorrect!).

I think you should be able to use the `--override` flag to get around `2`. Let me know if you've tried that and if it works for your use case!

**Comment by Eloquite** [comment]
Sorry about that, I seem to have missed the --override flag in the documentation. That does indeed fix my issue.
