### ISSUE TITLE
[feature] Filter download URLs to skip trackers

### ISSUE THREAD

**Issue by calebj** [lightpohl/podcast-dl#35]
My firewall is blocking a few hosts like podtrac and chartable by both IP and DNS, so I've had to add a few whitelist entries for the feeds to work on my regular podcatcher and this archiver. Someday I'll make my own proxy to strip them out of the feed on the fly, but I'm looking for an interim solution to this game of weekly whack-a-mole.

What would be the least obtrusive way to add a custom program (return filtered URL via stdout) or JS function that can take something like these atrocities
```
https://www.podtrac.com/pts/redirect.mp3/pdst.fm/e/chtbl.com/track/2H910/traffic.megaphone.fm/WWO0123456789.mp3?updated=1635179747
https://anchor.fm/s/6483d2f1/podcast/play/15934174/sponsor/d91uy9c/https%3A%2F%2Fd3cmojq1ktx6ya.cloudfront.net%2Fstaging%2F2021-06-21%2F60112d485e1c79b8d194a31f14d7f9ab.m4a
```
and reduce them to the megaphone and cloudfront URLs respectively? Since one is URL escaped and one isn't, this (sadly) isn't within the reach of regex. I would also need more samples to ensure a baked-in function covers all the possibilities for redirect URL chains.

---

Tangentially related, with the trove of podcast files I have now, I'm trying to think of ways to efficiently fingerprint and trim ads and other annoying segments/bumpers. That would feed back into the RSS proxy and hopefully work relatively hassle-free. It's way down the road, though.

**Comment by lightpohl** [comment]
Hey @calebj!

Sorry for the delayed response on this one!

Those trackers seem pretty annoying. I haven't really noticed them too much, but is it pretty common for the full podcast URL to be embedded in the tracking URL? And the embedded URL typically works by itself when pulled out?

This could be really neat idea — a new experimental flag (something like `--filter-url-trackers`) that attempts to grab the embedded URL at download time. Probably just need to work some regex magic or find a library that does it already.

I'll take a look here in a few days and see what we can do!

**Comment by calebj** [comment]
> [I]s it pretty common for the full podcast URL to be embedded in the tracking URL? And the embedded URL typically works by itself when pulled out?

In some form, and yes. I haven't tested to see if the trackers insert ads or just track downloads; odds are that it depends on how the publisher has it set up. I randomized parts of my example URLs in the first post for privacy, but here are some popular 'cast feeds:
- https://feeds.twit.tv/podcasts/ttg.xml
- https://anchor.fm/s/91c7948/podcast/rss
- https://feeds.megaphone.fm/stuffyoushouldknow

**Comment by lightpohl** [comment]
Thanks for the examples!

Added a simple version of this experimental flag in the [latest release](https://github.com/lightpohl/podcast-dl/releases/tag/v7.1.0). We need to validate the potential URLs before using them, so it adds some delay before the download starts. I wouldn't recommend using it unless you know the feed does this — validated with the feeds listed above.
