### ISSUE TITLE
Add OS binaries for v7

### ISSUE THREAD

**Issue by jimmybreeze** [lightpohl/podcast-dl#36]
Hello, I was wondering if there will be a version for Windows on the release page for version 7.0.0. Thanks!

**Comment by lightpohl** [comment]
Hey @jimmybreeze!

The project I was previously using for building the Node binaries for each OS was having some issues with some of the new modules being used for concurrent downloads. I would like to get the binaries added again relatively soon — need to explore some other options.

I'll keep you updated!

**Comment by lightpohl** [comment]
Binaries are finally back! Added to the last release page here: https://github.com/lightpohl/podcast-dl/releases
