### ISSUE TITLE
Download to temp files

### ISSUE THREAD

**Issue by MaienM** [lightpohl/podcast-dl#37]
Right now the files are downloaded directly to their destination. The downside of this is that if the process is interrupted you will end up with an incomplete file, but on the next run the download will be skipped because the file exists locally.

Downloading the files to a temp location/with a temp suffix (like some browsers do) and then moving/renaming once complete would fix this.

**Comment by lightpohl** [comment]
I like the idea! The file detection didn't used to be enabled by default, but it makes sense to add something like this now that it is. 👍

**Comment by lightpohl** [comment]
Added in v7.2! Thanks again!
