### ISSUE TITLE
Archive re-downloading podcast imagery

### ISSUE THREAD

**Issue by rickyeatough** [lightpohl/podcast-dl#39]
I'm using podcast-dl for periodically downloading multiple podcasts, and fetching new episodes each week (to be automatically uploaded to cloud and archived). I've got the `--archive` flag setup to output into a seperate JSON file for each podcast. 

Each time I run the downloader, even with the `--archive` flag, it re-downloads all podcast artwork again. Happens both when there is and when there _is not_ new episodes to be downloaded. 

Does the archive retain information on already downloaded podcast artwork? I'm also using the `--include-meta`, `--include-episode--meta` and `--out-dir` flags in each command.

**Comment by lightpohl** [comment]
The issue I found with the parent artwork should be fixed in the [latest release here](https://github.com/lightpohl/podcast-dl/releases/tag/v7.3.1). Let me know if you're still experiencing the issue after updating and we'll do some more troubleshooting!
