### ISSUE TITLE
Feature Request: File naming

### ISSUE THREAD

**Issue by garrettdowd** [lightpohl/podcast-dl#4]
Going along the same lines as the [youtube-dl output format](https://github.com/ytdl-org/youtube-dl#output-template) it would make sense to enable some file renaming.

This would enable more organized archiving, e.g. by automatically putting episodes in named podcast folders. Assuming other metadata could be extracted it would be nice to put the release date and duration in the filename among other things.

youtube-dl uses something like  `-o '%(podcast_name)s/%(release_date)s - %(title)s.%(ext)s`

**Comment by lightpohl** [comment]
This would be a great add. I like the keyword approach and if built correctly would be easy to extend with more keyword options.

I imagine I'll some time for this in the next few weeks. 👍

**Comment by lightpohl** [comment]
Added a simple version of this in the latest release with `--episode-template`. I think extending `--out-dir` to handle folder creation or using the podcast name automatically will be the likely path for better folder options.

**Comment by lightpohl** [comment]
`--out-dir` now supports basic templating options as well and will generate the folder if it doesn't exist. 👍
