### ISSUE TITLE
Automatically retry failed downloads

### ISSUE THREAD

**Issue by jolitti** [lightpohl/podcast-dl#41]
I'm bulk downloading several episodes, and ~5% of them timed out. Is there a way to re-download the selection while skipping the already downloaded ones or, alternatively, an option to retry failed downloads until completion?

**Comment by jolitti** [comment]
I re-launched the download and fortunately it already skips already downloaded episodes, which solves the problem. To completely automate the task, though, i wonder if an option to insist on a download until it's complete can be added.

Thank you

**Comment by lightpohl** [comment]
Hey! Yeah, it saves downloads to a `.tmp` file and then renames after it succeeds — so you can simply re-run the same command and it will only fetch items that failed.

Automatically retrying failed downloads could be a neat enhancement!

**Comment by lightpohl** [comment]
Finally added in [v9.0.0](https://github.com/lightpohl/podcast-dl/releases/tag/v9.0.0)! See the changlog for details. 👍
