### ISSUE TITLE
TimeoutError: Timeout awaiting 'request' for 5000ms

### ISSUE THREAD

**Issue by luckybencosmos** [lightpohl/podcast-dl#44]
I try to download a podcast of which the RSS address is: https://www.omnycontent.com/d/playlist/6dd8413b-ede6-483a-bf4e-ab80014939de/20f4bf02-d62f-40b2-b532-af10011ba71b/2bdbf0f4-e0ca-4343-9fb2-af10011ba729/podcast.rss

When I run `podcast-dl --url "https://www.omnycontent.com/d/playlist/6dd8413b-ede6-483a-bf4e-ab80014939de/20f4bf02-d62f-40b2-b532-af10011ba71b/2bdbf0f4-e0ca-4343-9fb2-af10011ba729/podcast.rss"`
I get 
> English Listening - Goals | Error downloading episode: TimeoutError: Timeout awaiting 'request' for 5000ms

But I can download metadata(json file).

I tried it both on Linux and Windows. The results is same.

I tried a url of an episode in the rss, for example:  https://omny.fm/shows/listening-time/english-listening-goals 
I can open this page, and click "Download" button in this page, and download this episode. 
I doubt this program copy the entire url in the `"<p>"` tag:  "https://omny.fm/shows/listening-time/english-listening-goals clean English Listening - Board Games English Listening - Board Games" . Because when I open this url, the web page tell me "The clip does not exist or may be private".

Could you fix it or is there any workaround?
I'm so appreciated.

---
By the way, if there is a template option to add list number, it would be better.

**Comment by lightpohl** [comment]
Hey @luckybencosmos! I was able to download episodes with that command, so I think it's simply a server response time issue. I bumped the timeout to 30 seconds [in v8.0.2](https://github.com/lightpohl/podcast-dl/releases/tag/v8.0.2). Would you mind giving that a try and see if it works for you?

> By the way, if there is a template option to add list number, it would be better.

Great request! I just added `episode_num` as a templating option for `--episode-template` if you'd like to use it! 👍

**Comment by luckybencosmos** [comment]
Hi, @lightpohl , I tried the newest version ([v8.0.2](https://github.com/lightpohl/podcast-dl/releases/tag/v8.0.2)), unfortunately, it still failed to download the audio. The error message is below:
```
English Listening - Goals | Error downloading episode: RequestError: connect ETIMEDOUT 162.125.32.6:443
```
But when I use `curl` to test, it seems normal. The detail is below:
` curl -i https://omny.fm/shows/listening-time/english-listening-goals`
```
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Date: Sun, 05 Feb 2023 09:03:39 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: public, max-age=15
vary: Accept-Encoding
content-security-policy: default-src 'self' https://omny.fm;connect-src 'self' https: https://*.googletagmanager.com https://*.google-analytics.com;script-src 'self' https://www.google-analytics.com https://ssl.google-analytics.com https://*.googletagmanager.com https://static.cloudflareinsights.com 'sha256-6pA+OLZkWFNcDsOkbEY8B8aF2uV+AHr8J3RzrTdq8j0=' https://connect.facebook.net;style-src 'self' 'unsafe-inline';font-src 'self';img-src 'self' data: https://www.omnycontent.com https:;media-src 'self' https:;worker-src 'none';object-src 'none'
Last-Modified: Sun, 05 Feb 2023 08:56:23 GMT
CF-Cache-Status: EXPIRED
Server: cloudflare
CF-RAY: 794a795cddb9895e-SIN
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
...
```
---
 `curl -i https://chtbl.com/track/4BC23E/dts.podtrac.com/redirect.mp3/traffic.omny.fm/d/clips/6dd8413b-ede6-483a-bf4e-ab80014939de/20f4bf02-d62f-40b2-b532-af10011ba71b/e57adf3e-ef6e-490d-af41-af86015e6e05/audio.mp3?download=true`  
```
HTTP/1.1 200 Connection established

HTTP/1.1 302 FOUND
Content-Type: text/html; charset=utf-8
Content-Length: 0
Connection: keep-alive
Date: Sun, 05 Feb 2023 09:01:05 GMT
Server: nginx/1.21.6
Location: https://dts.podtrac.com/redirect.mp3/traffic.omny.fm/d/clips/6dd8413b-ede6-483a-bf4e-ab80014939de/20f4bf02-d62f-40b2-b532-af10011ba71b/e57adf3e-ef6e-490d-af41-af86015e6e05/audio.mp3?download=true
Set-Cookie: _chtbl=f62adccf2add451f83a66764a250b96f; Domain=.chtbl.com; Path=/
Access-Control-Allow-Origin: *
X-Cache: Miss from cloudfront
Via: 1.1 f89fcc37b128414167e80016d2f77972.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: SIN52-C2
X-Amz-Cf-Id: wm8Pbx3cE7ya__WO3zH2iRs-aUjHQjt3HEF69pjttA7t9obm855tJQ==
```

**Comment by luckybencosmos** [comment]
Hi, I tried several new RSS url, it all showed this message:
```
Unable to parse RSS URL
connect ETIMEDOUT 151.101.110.110:443
```
It seems It's my network's problem. I currently using proxy via [Clash](https://github.com/Dreamacro/clash) to access these website. This software can only work on http and https, but don't work on Socket5. May be this is the problem?

**Comment by luckybencosmos** [comment]
I'm certain its my network's problem. I tried several URL, when `ping` command is working normal, I can download this episode. Otherwise, I can't.
I'm going to figure it out.
If you know the solution, please tell me.

**Comment by luckybencosmos** [comment]
I think the reason is this application can't use proxy, so I make a new issue, here is the link: https://github.com/lightpohl/podcast-dl/issues/45 .

**Comment by lightpohl** [comment]
Thanks for the info! Closing this issue and continuing in #45.
