### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by luckybencosmos** [lightpohl/podcast-dl#45]
Hi, I found "got" package already support proxy, here is the detail link: https://github.com/sindresorhus/got/blob/main/documentation/tips.md#proxying . 

There seems to have an another way which is using [global-agent](https://github.com/gajus/global-agent) . 

Here is also a solution by using "http" package. https://stackoverflow.com/questions/3862813/how-can-i-use-an-http-proxy-with-node-js-http-client 

Could you support this function? May be let users use it via command line options.

**Comment by lightpohl** [comment]
Hey! Thanks for looking into this — I just pushed up a some test binaries with support for a `--proxy` option using global-agent. Would you mind giving the Linux binary of the release below a try? You'll need to pass in the right environment variables and include the `--proxy` flag to podcast-dl to turn it on.

https://github.com/lightpohl/podcast-dl/releases/tag/v8.1.0-proxy.0

Let me know how it goes and I'll get it included in a main release. 👍

**Comment by lightpohl** [comment]
Hello again! Hope all is well!

Went ahead and added this to an official version: [v8.0.3](https://github.com/lightpohl/podcast-dl/releases/tag/v8.0.3)

**Comment by aureq** [comment]
@lightpohl Happy to report the proxy support works really well 🎉

I only had to set `GLOBAL_AGENT_ENVIRONMENT_VARIABLE_NAMESPACE=` so `global-agent` would recognize `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` variables automatically.
