### ISSUE TITLE
Option `episode-digits` has no effect on `episode-image` or `episode-meta`

### ISSUE THREAD

**Issue by rdwz** [lightpohl/podcast-dl#52]
**example**

`npx podcast-dl --episode-digits 2 --episode-template "{{episode_num}}" --include-episode-images --include-episode-meta ...`

**result**

> 01.mp3
> 1.meta.json
> 1.jpg

**Comment by lightpohl** [comment]
Thank you for the report, @rdwz! This has been resolved in v8.0.7. 💪

https://github.com/lightpohl/podcast-dl/releases/tag/v8.0.7
