### ISSUE TITLE
Only downloads last 100 episodes

### ISSUE THREAD

**Issue by hemicyon** [lightpohl/podcast-dl#55]
Using the RSS link with podcast-dl only downloads the last 100 episodes. All the episodes are available on the Overcast app, but every other podcast app only shows the last 100. This is an issue with SquareSpace, but I'm wondering if there's a workaround. 

The link in question
http://www.hellointernet.fm/podcast?format=rss

**Comment by lightpohl** [comment]
Hey there! I believe Overcast crawlers cache the RSS feed over time so it's able to access older episodes if they're still available. `podcast-dl` only knows about items returned when it's run so it can't find those older episodes unfortunately.

You might be able to point a more flexible download script (like `youtube-dl`) at this `libsyn` page to grab them all in one go (or you can download the missing items manually!).

https://hellointernet.libsyn.com/page/1/size/200

**Comment by mchill** [comment]
I follow a couple of podcasts that do this as well. I ended up using the [Wayback Machine](https://web.archive.org/web/). You can enter the url for your rss feed, find a version old enough to still have old episodes, and then get the raw cached file by inspecting the network requests in your browser.

This cached [feed](https://web.archive.org/web/20160308174243if_/http://www.hellointernet.fm/podcast?format=rss) has all the old episodes you're looking for.
