### ISSUE TITLE
Support ffmpeg for more file types

### ISSUE THREAD

**Issue by mchill** [lightpohl/podcast-dl#57]
CLI options that use ffmpeg currently aren't allowed to run for non-mp3 files because of [this check](https://github.com/lightpohl/podcast-dl/blob/main/bin/util.js#L455). ID3 tags are [supported](https://en.wikipedia.org/wiki/ID3#Non-MP3_implementation) by other file types, so it would be nice to widen that restriction to include a few other common file types found in podcast feeds.

I tested it out locally with a few .m4a files, and writing metadata works fine. I can make the change if you're okay with it.

**Comment by lightpohl** [comment]
Thank you for taking a look!

I would be more than happy to accept a PR for it!

**Comment by lightpohl** [comment]
Thanks again! Your work is available in [v9.1.0](https://github.com/lightpohl/podcast-dl/releases/tag/v9.1.0). 💪
