### ISSUE TITLE
Feature request: out-dir Templating options

### ISSUE THREAD

**Issue by jawhett** [lightpohl/podcast-dl#59]
I would like my Podcasts to be structured as follows Podcast title Folder-> Episode title  Folder -> Episode with image

Ideally because Jellyfin doesnt have a podcast library support but this file Structure would present the The Podcast as the Author, and each podcast as a book.  

This lets Jellyfin's book Library Work Great. 

This is what I am trying to do: 
npx podcast-dl --limit 2 --url https://lexfridman.com/feed/podcast/ --include-episode-images --episode-template "{{title}}" --out-dir "./{{podcast_title}}/{{title}}"

**Comment by lightpohl** [comment]
Take a look at [v9.2.0](https://github.com/lightpohl/podcast-dl/releases/tag/v9.2.0) for the behavior change!

Added an example [here](https://github.com/lightpohl/podcast-dl/blob/v9.2.0/docs/examples.md#download-all-episodes-to-their-own-directory) as well. 👍
