### ISSUE TITLE
Escape all metadata params passed into ffmpeg when using '--add-mp3-metadata'

### ISSUE THREAD

**Issue by binyaminyblatt** [lightpohl/podcast-dl#60]
'amp' is not recognized as an internal or external command,
operable program or batch file.

` The 12 Deaths of Christmas - Day 1 | Error downloading episode: Error: Command failed: ffmpeg -loglevel quiet -i "D:\Media\Podcasts\The Amelia Project Patreon Feed\20231225-The 12 Deaths of Christmas - Day 1.mp3" -map_metadata 0 -metadata album="The Amelia Project Patreon Feed" -metadata title="The 12 Deaths of Christmas - Day 1" -metadata comment="<p>\"For the next two weeks this case will take over our lives!\"</p><p><img data-media-id=\"258530827\"></p><p>WISHING YOU THE HAPPIEST OF HOLIDAYS dear patrons!</p><p>We'll be accompanying you over the next two weeks with daily instalments of the bonus miniseries <strong>The 12 Deaths of Christmas.</strong></p><p>It chronicles one of the most bonkers cases The Amelia Project has ever taken on. Tune in daily for the spiralling chaos...</p><p>If you haven't done so yet, do check out the <a href=\"https://www.patreon.com/posts/taking-you-93046568?utm_medium=clipboard_copy&amp;utm_source=copyLink&amp;utm_campaign=postshare_creator&amp;utm_content=join_link\">patron exclusive Behind the Scenes video for this series! </a></p><p>We will be collecting three pledges for this miniseries, one in December, two in January. Thank you so much for your support and allowing us to keep making this show!</p><p>Happy listening! Love &amp; Cocoa!</p><p>The Amelia Team  💝</p><p>Website: <a href=\"https://ameliapodcast.com/\" rel=\"nofollow noopener\" target=\"_blank\">https://ameliapodcast.com/</a></p><p>Transcripts: <a href=\"https://ameliapodcast.com/season-5\" rel=\"nofollow noopener\" target=\"_blank\">https://ameliapodcast.com/season-5</a></p><p>Merch: <a href=\"https://www.teepublic.com/stores/the-amelia-project?ref_id=6148\" rel=\"nofollow noopener\" target=\"_blank\">https://www.teepublic.com/stores/the-amelia-project?ref_id=6148</a></p><p>Instagram: <a href=\"https://www.instagram.com/ameliapodcast/\" rel=\"nofollow noopener\" target=\"_blank\">https://www.instagram.com/ameliapodcast/</a></p><p>Tumblr: <a href=\"https://www.tumblr.com/ameliapodcast\" rel=\"nofollow noopener\" target=\"_blank\">https://www.tumblr.com/ameliapodcast</a></p><p>X: <a href=\"https://twitter.com/amelia_podcast\" rel=\"nofollow noopener\" target=\"_blank\">https://twitter.com/amelia_podcast</a></p><p>Bluesky: <a href=\"https://bsky.app/profile/theameliaproject.bsky.social\" rel=\"nofollow noopener\" target=\"_blank\">https://bsky.app/profile/theameliaproject.bsky.social</a></p>" -metadata track="157" -metadata date="2023-12-25" -codec copy "D:\Media\Podcasts\The Amelia Project Patreon Feed\20231225-The 12 Deaths of Christmas - Day 1.mp3.tmp.mp3"`

**Comment by lightpohl** [comment]
Thanks for the report! Looks like we need to escape the parameters passed into `ffmpeg` when using `--add-mp3-metadata`.

If you want to avoid the error for now, you can simply drop that flag from your run for that podcast feed and you should be okay!

**Comment by lightpohl** [comment]
Try out the latest version and see how it goes on that Patreon feed! https://github.com/lightpohl/podcast-dl/releases/tag/v9.2.1

**Comment by binyaminyblatt** [comment]
Thanks

**Comment by binyaminyblatt** [comment]
i just tryd  it and got this error 

`ffmpeg -loglevel quiet -i "D:\Media\Podcasts\The Amelia Project Patreon Feed\20210318-Composer’s Corner - Amelia Death Metal for Episode 8.mp3" -map_metadata 0 -metadata album='The Amelia Project Patreon Feed' -metadata title='Composer’s Corner - Amelia Death Metal for Episode 8' -metadata comment='<p>Hello dear patrons,</p><p>Some of you have asked for downloadable versions of the theme tune variations. So over the coming weeks we’ll be sharing them here on Patreon! We’ll also give a bit of context about each one…</p><p>Today: the metal version (still one of our absolute favourites)</p><p>Oystein and I knew from the beginning that we wanted to have fun with the music. We love to riff on different genres when we write episodes (crime, mystery, sci-fi etc) and we thought the music should do the same. Our aim has always been to create a show that keeps listeners on their toes and in which each episode contains a surprise.</p><p>For episode 8 “Luke Dougal” (the one in the Hell Park) we asked Fredrik Baden (the composer) to create a sort of Hammer Horror haunted house score, something with organ, gongs and thunderclaps.</p><p>Freddy went off, ignored all of our directions, and did something completely different instead. Something much better. A heavy metal version!</p><p>This is why we love working with Freddy. In the same way we aim to surprise listeners, Freddy surprises <em>us!</em></p><p>I still remember receiving the first draft of this composition, clicking play (unprepared for what was coming, my headphones turned up way too loud) and having Amelia Death Metal blow my head off.</p><p>I really like the fact that the very first time we start an episode with a theme variation, it’s something this big and brash and bold!</p><p>Although I feel I must apologise to the listener who wrote in to say she enjoys the show on her morning runs, and when the death metal theme kicked in she was so surprised she almost ran into a canal…</p><p>If you have any memories of listening to this variation we’d love to know in the comments below!</p><p>Anyway, over to Freddy himself to give you some musical nitty gritty:</p><p><em>Heyo, peeps and peepettes!</em></p><p><em>What Pip said is perfectly true. However, I </em>did<em> voice my concern about using the organ as a main instrument so soon after the «fugal» funeral scene in Steve (which we’ll come back to in a different Composer’s Corner). So, thinking of what else could represent Hell, naturally, death metal felt only natural.</em></p><p><em>I’ve talked about this theme before, but I don’t think I’ve pointed at the two obvious inspirations for this little piece:</em></p><p><em>1 - Dimmu Borgir - Progenies of the Apocalypse</em></p><p><em>My fellow countrymen are world renowned in the death metal genre, but I’ve never been very into it myself. However, the symphonic intro to this song completely blew me away the first time I heard it. Or, </em>saw<em> it actually - a drummer friend of mine in high school had burned me a CD-ROM (yes, I’m that old) with videos of drumming to aspire to. The resolution was comparable to the tiles on my bathroom floor, but I remember the need to head bang to this video! When thinking about how to go about making an epic intro for myself, this came back to me all these years later.</em></p><p><a href="https://www.youtube.com/watch?v=AaGbkvPrioU" rel="nofollow noopener" target="_blank"><em>Music video</em></a><em> - Viewer discretion: insane amount of screen shake, goat blood and strobe light. (And tiddies…)</em></p><p><em>2 - Without realising it, I completely ripped off the ending of the Buffy the Vampire Slayer theme for my own ending! We think that my girlfriend was re-binging the whole series around that time, or earlier, so it’s entirely possible that’s why. In any case, it’s a wonderful punk theme and I feel stupid to not have added the church bell at the last chord in my variation…</em></p><p><a href="https://www.youtube.com/watch?v=5-xnvdtuRRo&amp;t=124s" rel="nofollow noopener" target="_blank"><em>Music video</em></a></p><p><em>That’s all for this time. Reach out if you’re wondering about anything :)</em></p><p><em>Freddy</em></p>' -metadata track=75 -metadata date=2021-03-18 -codec copy "D:\Media\Podcasts\The Amelia Project Patreon Feed\20210318-Composer’s Corner - Amelia Death Metal for Episode 8.mp3.tmp.mp3"
< was unexpected at this time.`

**Comment by lightpohl** [comment]
Ah, okay! I think this is probably OS/prompt specific. Mind answering a couple questions for me?

- Which OS are you running?
- Are you using bash? zsh? Something different?
- Are you running it via npm or a binary?

**Comment by binyaminyblatt** [comment]
windows binary

**Comment by binyaminyblatt** [comment]
btw i love this tool thanks for all ur hard work

**Comment by lightpohl** [comment]
Thank you! I'll recreate on Windows and get a better patch out — one last question: Command Prompt or PowerShell to run it?

**Comment by binyaminyblatt** [comment]
Command Prompt

**Comment by lightpohl** [comment]
Okay! Updated the script so slightly less info is copied over in the metadata in Windows depending on how complex the escape sequence is. Give this new version and shot!

https://github.com/lightpohl/podcast-dl/releases/tag/v9.2.2
