### ISSUE TITLE
Escape all metadata params passed into ffmpeg when using '--add-mp3-metadata

### ISSUE THREAD

**Issue by binyaminyblatt** [lightpohl/podcast-dl#62]
i just tryd https://github.com/lightpohl/podcast-dl/releases/tag/v9.2.1 and got this error 
i cant reopen #60 
so im making a new issue

`ffmpeg -loglevel quiet -i "D:\Media\Podcasts\The Amelia Project Patreon Feed\20210318-Composer’s Corner - Amelia Death Metal for Episode 8.mp3" -map_metadata 0 -metadata album='The Amelia Project Patreon Feed' -metadata title='Composer’s Corner - Amelia Death Metal for Episode 8' -metadata comment='<p>Hello dear patrons,</p><p>Some of you have asked for downloadable versions of the theme tune variations. So over the coming weeks we’ll be sharing them here on Patreon! We’ll also give a bit of context about each one…</p><p>Today: the metal version (still one of our absolute favourites)</p><p>Oystein and I knew from the beginning that we wanted to have fun with the music. We love to riff on different genres when we write episodes (crime, mystery, sci-fi etc) and we thought the music should do the same. Our aim has always been to create a show that keeps listeners on their toes and in which each episode contains a surprise.</p><p>For episode 8 “Luke Dougal” (the one in the Hell Park) we asked Fredrik Baden (the composer) to create a sort of Hammer Horror haunted house score, something with organ, gongs and thunderclaps.</p><p>Freddy went off, ignored all of our directions, and did something completely different instead. Something much better. A heavy metal version!</p><p>This is why we love working with Freddy. In the same way we aim to surprise listeners, Freddy surprises <em>us!</em></p><p>I still remember receiving the first draft of this composition, clicking play (unprepared for what was coming, my headphones turned up way too loud) and having Amelia Death Metal blow my head off.</p><p>I really like the fact that the very first time we start an episode with a theme variation, it’s something this big and brash and bold!</p><p>Although I feel I must apologise to the listener who wrote in to say she enjoys the show on her morning runs, and when the death metal theme kicked in she was so surprised she almost ran into a canal…</p><p>If you have any memories of listening to this variation we’d love to know in the comments below!</p><p>Anyway, over to Freddy himself to give you some musical nitty gritty:</p><p><em>Heyo, peeps and peepettes!</em></p><p><em>What Pip said is perfectly true. However, I </em>did<em> voice my concern about using the organ as a main instrument so soon after the «fugal» funeral scene in Steve (which we’ll come back to in a different Composer’s Corner). So, thinking of what else could represent Hell, naturally, death metal felt only natural.</em></p><p><em>I’ve talked about this theme before, but I don’t think I’ve pointed at the two obvious inspirations for this little piece:</em></p><p><em>1 - Dimmu Borgir - Progenies of the Apocalypse</em></p><p><em>My fellow countrymen are world renowned in the death metal genre, but I’ve never been very into it myself. However, the symphonic intro to this song completely blew me away the first time I heard it. Or, </em>saw<em> it actually - a drummer friend of mine in high school had burned me a CD-ROM (yes, I’m that old) with videos of drumming to aspire to. The resolution was comparable to the tiles on my bathroom floor, but I remember the need to head bang to this video! When thinking about how to go about making an epic intro for myself, this came back to me all these years later.</em></p><p><a href="https://www.youtube.com/watch?v=AaGbkvPrioU" rel="nofollow noopener" target="_blank"><em>Music video</em></a><em> - Viewer discretion: insane amount of screen shake, goat blood and strobe light. (And tiddies…)</em></p><p><em>2 - Without realising it, I completely ripped off the ending of the Buffy the Vampire Slayer theme for my own ending! We think that my girlfriend was re-binging the whole series around that time, or earlier, so it’s entirely possible that’s why. In any case, it’s a wonderful punk theme and I feel stupid to not have added the church bell at the last chord in my variation…</em></p><p><a href="https://www.youtube.com/watch?v=5-xnvdtuRRo&amp;t=124s" rel="nofollow noopener" target="_blank"><em>Music video</em></a></p><p><em>That’s all for this time. Reach out if you’re wondering about anything :)</em></p><p><em>Freddy</em></p>' -metadata track=75 -metadata date=2021-03-18 -codec copy "D:\Media\Podcasts\The Amelia Project Patreon Feed\20210318-Composer’s Corner - Amelia Death Metal for Episode 8.mp3.tmp.mp3" < was unexpected at this time.`

**Comment by lightpohl** [comment]
Hey! I responded in the old issue. If you answer there I'll reopen the issue. Closing this one!
