### ISSUE TITLE
Feature Request: Download RSS podcast using Local RSS file

### ISSUE THREAD

**Issue by AlphaHasher** [lightpohl/podcast-dl#64]
As the title says, it would be great to be able to pass an RSS file that you have locally because the RSS feed that I want to download sometimes includes broken & bad metadata, and instead of manually editing the metadata of each audio file, to pass an edited RSS file (that I downloaded and edited) through the CLI?

**Comment by lightpohl** [comment]
Hey! That would be a fun addition — once thing that holds it back is that the RSS parser library `podcast-dl` uses doesn't support local files, so it would need to duplicate the parsing for local files. I'll keep pondering the best way to add something like that though.

If you're looking for a workaround, you can host the local file and point `podcast-dl` to it! For example, this is how it would work with `npx`.

```
# inside the directory of my-custom-rss.xml
npx http-server
```

```
# in a separate terminal
podcast-dl --url "http://127.0.0.1:8080/my-custom-rss.xml"
```

**Comment by lightpohl** [comment]
Hey again! This ended up being easier than I expected with the latest version — added the `--file` param to the `v9.3.0` release. Available here! https://github.com/lightpohl/podcast-dl/releases/tag/v9.3.0
