### ISSUE TITLE
Can mp3/m4a files be downloaded from podcast links directly?

### ISSUE THREAD

**Issue by lyra-white** [lightpohl/podcast-dl#67]
Hi @lightpohl and team, and thank you for this awesome project. I can totally see it grow a lot.
I am wondering if podcasts can be downloaded from the podcast url and not RSS url. 

Example of podcast urls: 

1. https://open.spotify.com/show/5VzFvh1JlEhBMS6ZHZ8CNO
2. https://podcasts.apple.com/us/podcast/the-scarecast/id1071545581

or more similar.

**Comment by lightpohl** [comment]
Hey there! With some detective work (or using a web tool like this this one: https://www.labnol.org/podcast/), you can find the RSS URL from the iTunes page! I don't think you can via Spotify though.

For example, the RSS link for the show you linked would be the following: https://feeds.redcircle.com/1a5a2b50-ba56-48fc-a05b-ce2a55cac801
