### ISSUE TITLE
DL from radio station's xml-feed leads into errors rather than dowloads

### ISSUE THREAD

**Issue by MasterP-theGu** [lightpohl/podcast-dl#70]
Hi lightpohl,

thank you so much for this great tool! I really do enjoy every update, so cheers again.

I don't use too many different podcasts to download, but I keep running into issues with this one:

https://www.ndr.de/podcast/podcast4336.xml

I get:

`
(node:5527) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL: undefined
    at new NodeError (internal/errors.js:322:7)
    at onParseError (internal/url.js:270:9)
    at new URL (internal/url.js:346:5)
    at /snapshot/dist/podcast-dl-9.3.2.js
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `podcast-dl --trace-warnings ...` to show where the warning was created)
(node:5527) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5527) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`
and --trace-warnings is an "unknown option". Hm.

The problem is most likely the human sitting at my keyboard, but he'd also be very grateful for a hint in which direction to go for the xml-feed to work.

Thanks and all the very best!

**Comment by lightpohl** [comment]
Thank you for the bug report! The RSS parser couldn't find the `feedUrl` on its own, but I added a fallback that should get that feed working for you. 👍

The fix is now available in the latest release! https://github.com/lightpohl/podcast-dl/releases/tag/v9.3.3

**Comment by MasterP-theGu** [comment]
Thank you so much, lightpohl, it runs smoothly and makes me very happy. :smile:
