### ISSUE TITLE
Modifying Episode Numbers in podcast-dl

### ISSUE THREAD

**Issue by minnas23** [lightpohl/podcast-dl#74]
Hello! I'd like to discuss how to dynamically adjust the `episode_num` value in the following PowerShell command for the **podcast-dl** tool:

```powershell
& ".\podcast-dl-9.3.4-win-x64.exe" --url https://feeds.buzzsprout.com/100.rss --out-dir ".\Buzzsprout_Podcast\" --episode-template "{{episode_num}}. {{title}}" --archive ".\resources\Buzzsprout_Podcast\archive.json" --episode-digits 3 --reverse
```

For example, I want to achieve the following variations:

1. **Increment Episode Number**:
   - Command: 
     ```powershell
     & ".\podcast-dl-9.3.4-win-x64.exe" --url https://feeds.buzzsprout.com/100.rss --out-dir ".\Buzzsprout_Podcast\" --episode-template "{{episode_num + 2}}. {{title}}" --archive ".\resources\Buzzsprout_Podcast\archive.json" --episode-digits 3 --reverse
     ```
   - Expected Result: The `episode_num` will be incremented by 2.

2. **Decrement Episode Number**:
   - Command:
     ```powershell
     & ".\podcast-dl-9.3.4-win-x64.exe" --url https://feeds.buzzsprout.com/100.rss --out-dir ".\Buzzsprout_Podcast\" --episode-template "{{episode_num - 2}}. {{title}}" --archive ".\resources\Buzzsprout_Podcast\archive.json" --episode-digits 3 --reverse
     ```
   - Expected Result: The `episode_num` will be decremented by 2.

Is there a way to achieve this in **podcast-dl**? If so, how can I use it?

**Comment by lightpohl** [comment]
Sorry for the delay! `podcast-dl` can now accommodate this with the new config option `episode-num-offset` [available in v9.4.0](https://github.com/lightpohl/podcast-dl/releases/tag/v9.4.0).

`./podcast-dl.exe  --url "https://feeds.buzzsprout.com/100.rss" --episode-num-offset 0  --episode-template "{{episode_num}}. {{title}}"`
