### ISSUE TITLE
Support more template option in --episode-template

### ISSUE THREAD

**Issue by minnas23** [lightpohl/podcast-dl#78]
Hello. Thank you for support me in [here](https://github.com/lightpohl/podcast-dl/issues/74). 

Thank you so much for creating this great tool. It really helped me a lot. Below are my ideas. I know there are quite a few ideas listed below, so you can slowly add them to podcast-dl. Good things take time :)

**1. Can you add support for characters other than english characters in --episode-template?**

In the code below, the file name when downloaded does not display the correct characters that I used in --episode-template ( "ậ" and "：") . Can you add support UTF-8 and special character to --episode-template?

`& ".\podcast-dl-9.5.0-win-x64.exe" --url https://feeds.buzzsprout.com/100.rss --episode-num-offset 0 --out-dir "D:\new podcast dl\100\file" --episode-template "Tập {{episode_num}}：{{title}} ({{release_date}})" --archive "D:\new podcast dl\100\archive.json" --episode-digits 3 --reverse --after "09/20/2021"`

**2. Can you add a feature to automatically replace special characters in Windows with replacement characters (most commonly :, ? and /) in file name when the file is downloaded like yt-dlp?**

For example file name is: 

> "Test" | Tiltle?

podcast-dl will change to: 

> ＂Test＂ ｜ Tiltle？

 And when used special characters in --episode-template, podcast-dl will automatically convert those characters into replacement characters

For example I use ":", a character not allowed in Windows in --episode-template:

`--episode-template "Episode: Before-Title {{title}} ({{release_date}})"`

podcast-dl will change filename when downloaded to (replace ":" to "：") : 

> Episode： Before-Title Title (20210725)

Below are the characters that yt-dlp used to replace special characters:
`<>:"/\|?*` (here is character not allowed in filename in Windows)
`＜＞：＂⧸⧹｜？＊` (here is character yt-dlp use to replace characters above)

**3. Added support for --episode-num-offset**

I want to use --episode-num-offset to do podcast episode numbering for podcast episodes that have been deleted properly

For example: https://feeds.buzzsprout.com/100.rss
The first 6 episodes of this podcast are: (in --reverse mode)
```
"Why Church Still Works"
Only By Grace
Good Question
It's a Well
Promise of the Savior
Jesus Was a Teenager
```

If "It's a Well" is removed, I want the offsets in {{episode_num}} to still be numbered properly when running this command

`& ".\podcast-dl-9.5.0-win-x64.exe" --url https://feeds.buzzsprout.com/100.rss --episode-num-offset 0 --out-dir "D :\new podcast dl\100\file" --episode-template "{{episode_num}}. {{title}}" --archive "D:\new podcast dl\100\archive.json" --episode-digits 3 --reverse"`

The result will still be:
```
001. "Why Church Still Works"
002. Only By Grace
003. Good Question
005. Promise of the Savior
006. Jesus Was a Teenager
```

Is there any way to do this? For example, add an "If" option to --episode-num-offset? (If `--offset < 4`, `--episode-num-offset 0`, If `--offset > 5`,  `--episode-num-offset 1`. You can add feature to support more than 2 "If" I write).

**4. Support automatically get file year information of file and creates year directory in --episode-template (eg: D:\2021\filename)**

```
# Download YouTube playlist videos in separate directories according to their uploaded year
$ yt-dlp -o "%(upload_date>%Y)s/%(title)s.%(ext)s" "https://www.youtube.com/playlist?list=PLwiyx1dc3P2JR9N8gQaQN_BCvlSlap7re"
```

The above command is the command yt-dlp will download video and save it to directories according to their uploaded year.

Can you add an feature for podcast-dl to get the year of the file and then automatically create a path and download the file to that path similar to `"%(upload_date>%Y)s/%(title)s.%(ext)s"` of yt-dlp command above?

such as this
`--episode-template "D:\%(upload_date>%Y)s\{{episode_num}}. {{title}} ({{release_date}})"`

This is Output Template of yt-dlp:
https://github.com/yt-dlp/yt-dlp/tree/master?tab=readme-ov-file#output-template-examples

**5. Support `auto_number` in --episode-template besides `episode_num`**

`yt-dlp --autonumber-start 5 -o "%(autonumber)03d. %(title)s.%(ext)s" <URL>`

The above command is the command yt-dlp will download video with number padded with leading zeros to 3 digits (001, 002,...) combined with the option to select the automatic numbering start number (for example in the code above, the title of the first video downloaded will be `005. Title.mp4`

Can you add this option to --episode-template? Such as this
`--episode-template "D:\{{auto_number}}. {{title}} ({{release_date}})" --autonumber-start 5`

**Comment by lightpohl** [comment]
Hey! Apologies for the delay — been AFK from the personal keyboard for a bit.

> 1. Can you add support for characters other than english characters in --episode-template?

The issue you're seeing with `Tập` seems to be related to Windows and/or the terminal you're using to call `podcast-dl`. When running the same episode on my Mac, I've able to see the correctly generated filenames based on the template.

> 2. Can you add a feature to automatically replace special characters in Windows with replacement characters (most commonly :, ? and /) in file name when the file is downloaded like yt-dlp?

This seems to be related to Windows/the terminal app as well. `podcast-dl` uses an [existing project to escape unsafe characters in filenames](https://github.com/sindresorhus/filenamify), and it seems to be working correctly when the characters make it into `podcast-dl`. You might need to look into escaping those characters in the terminal arguments?

> 3. Added support for --episode-num-offset

If the files no longer exist in the RSS feed, there's not really much `podcast-dl` can do. Depending on the podcast, you might be able to use the new `[--episode-custom-template-options](https://github.com/lightpohl/podcast-dl/tree/v10.0.0?tab=readme-ov-file#--episode-custom-template-options)` to extract the episode number from the episode title.

> 4. Support automatically get file year information of file and creates year directory in --episode-template (eg: D:\2021\filename)

This is doable! I can add a `podcast_year` option for the `--out-dir` param.

> 5. Support auto_number in --episode-template besides episode_num

This is currently available, but requires two params: `--episode-num-offset 5 --episode-digits 3`.

**Comment by lightpohl** [comment]
Created a new issue for `podcast_year1`: https://github.com/lightpohl/podcast-dl/issues/81

**Comment by lightpohl** [comment]
Definitely feel free to include more information/troubleshooting steps for the Windows issue and I'll see if I find a workaround for ya!
