### ISSUE TITLE
Does not create nested directories

### ISSUE THREAD

**Issue by garrettdowd** [lightpohl/podcast-dl#8]
podcast-dl v1.6.1

podcast-dl does not create directories when `--out-dir` is given a filepath with directories that do not exist.

For example, given `--out-dir ~/Downloads/test/{{podcast_title}}` and if `~/Downloads/test/` does not exist then the command will fail rather than creating the the directory.

I was thinking the expected behavior would be to create the directory tree since it is explicitly given by the user (similar to mkdir -p). Although this could also be a safety feature to prevent downloading to incorrect locations.

**Comment by lightpohl** [comment]
Hey! I realized after you made this issue that Node added a recursive folder create method that I didn't know about. I'll add it soon and include it in the next breaking release. 👍
