### ISSUE TITLE
Idea: Make podcast {{url}} available to exec command

### ISSUE THREAD

**Issue by naltmann** [lightpohl/podcast-dl#84]
My use case is certainly an uncommon one (substituting individual podcast episode urls in the source xml file), but having the {{url}} available to the exec command might be useful for others as well.

**Comment by lightpohl** [comment]
Seems reasonable to me! `url` is now available to `--exec` in [v10.3.0](https://github.com/lightpohl/podcast-dl/releases/tag/v10.3.0).

For my own curiosity: what did end up using the substituted url for?
