### ISSUE TITLE
Feature request - skip existing episodes

### ISSUE THREAD

**Issue by paulhaddon** [lightpohl/podcast-dl#9]
A useful feature to keep podcasts up to date would be the ability to skip downloading episodes already on disk.

**Comment by lightpohl** [comment]
Hey @paulhaddon,

You can accomplish this by using the `--archive` option when starting a download. On following runs of the CLI, if you point at the previous archive file it'll check if a particular episode was downloaded and skip it if found.

`./podcast-dl --url <URL> --archive "./archive.json"`

**Comment by lightpohl** [comment]
Hey again @paulhaddon,

Ended up revisiting this today and updated the behaviour for v3. Now the default behaviour is to skip any collisions locally. You can get the previous behaviour using the new `--override` flag. :+1:
