### ISSUE TITLE
NOT operator for --episode-regex to filter downloads

### ISSUE THREAD

**Issue by StevenAston** [lightpohl/podcast-dl#91]
It would be nice if the --episode-regex function either allowed you to exclude or include episodes to download based on a flag, or if there was just a separate function like --episode-regex-exclude for example that allowed you to filter out certain entries.

Many podcasts have episode titles that have no reoccurring pattern but include [TEASER] or short promotional 'episodes' that I doubt many people want. Some feeds also carry mini series etc.

I don't think there's any closed issues that address this and I'm not a regex expert so forgive me if there's a way to do this that I've missed and thank you for the project :)

**Comment by lightpohl** [comment]
Hey! I'm also not a regex export so no need to apologize! I attempted to get something working with a negative [lookahead](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Lookahead_assertion) but getting it passed in via the command line is not fun.

I'll give it another shot when I have more time and explore other options as well. 💪

**Comment by StevenAston** [comment]
Thanks for the response, I did actually manage to get the results I wanted with a negative lookahead after a little tinkering. I still think it might make a good feature but it is possible with the software as-is. In case anyone else is struggling with the same issue, what ended up working for me was this:

Say this is our podcast list and we want to download everything except the 'Miniseries' episodes

>221 - Valora Dei Cantoros.mp3
>33 - Miniseries - Fenara Vel Chroniras.mp3
>222 - Thalor Im Brenivar.mp3
>223 - Lorien Ves Erenthos.mp3
>34 - Miniseries - Murios of Sylvenar.mp3
>224 - Arvenar Nocet Lurai.mp3
>225 - Trevaris Un Dianthros.mp3
>35 - Miniseries - Cyranthos Am Brevalor.mp3

we can use negative lookahead like so `--episode-regex="\d*\s\-\s(?!Miniseries)"` where the `\d*\s\-\s` grabs (0-9) however many times, plus the " - " and then the `(?!Miniseries)` part looks for "Miniseries" and returns 'false' if it finds it, so only episodes 221, 222, etc will be grabbed. Hopefully someone finds that helpful.

**Comment by lightpohl** [comment]
I added `--episode-regex-exclude` to the latest release, which should make this much easier moving forward. Glad you were able to get something working in the mean time! 

https://github.com/lightpohl/podcast-dl/pull/94
