### ISSUE TITLE
Filename is not escaped when passing to ffmpeg?

### ISSUE THREAD

**Issue by ndouglas** [lightpohl/podcast-dl#95]
Similar to #60. This is occurring on Linux, executed from `bash`.

I'll get an error indicating that `ffmpeg` failed, but of course there's not much output from `ffmpeg` to go off of. Running the command manually, without the `--quiet`, I'll get an error like `<path>/blah-blah-blah 5 blah-blah-blah.mp3: No such file or directory`

The path of the existing file will be something like `<path>/blah-blah-blah $25 blah-blah-blah.mp3`. In other words, the filename is passed with double quotes, `$2` will be expanded into a variable (which in this case evaluates to nothing), and then the remaining string doesn't correspond to a file in the filesystem.

It's possible that I'm getting a misleading representation of the `ffmpeg` command, since I'm relying on a log delivered to me from another system. But if I manually run the same command, escaping the `$`, it succeeds, so there doesn't seem to be another error that is masked by this one.

If I'm reading the code correctly [1], it appears that the filename is not escaped, so special characters like `$` can be expanded inadvertently. I'm about to head off to work, but I might have enough time to open a PR this weekend.

I love `podcast-dl`, BTW. Thank you for your work.

[1] https://github.com/lightpohl/podcast-dl/blob/7a54937644f3737a54f744e3e1899e1b08fdef4e/bin/util.js#L616

**Comment by lightpohl** [comment]
Hey  @ndouglas! Sorry you're running into trouble with that command!

The `outputPath` should hopefully (🤞) be escaped by the time it makes it to `runFfmpeg`. When you have a few minutes, would you mind sharing the exact command you're using to run `podcast-dl` where this error occurs? If it's a private feed, feel free to leave off the `--url` of course!

**Comment by ndouglas** [comment]
Sure. I have lists of podcasts (as said, I get a lot of value out of `podcast-dl` 🙂) that get processed on a schedule with these two Bash functions:

```
pod_download_new() {
  : "${1?"Usage: ${FUNCNAME} ROOT_DIRECTORY"}";
  root_directory="${1}";
  # Combine the lists, filter out duplicates, and sort randomly to avoid fatal errors blocking download progress over multiple runs
  awk '!/^ *#/ && NF' ~/.config/podcast-dl/podcasts.*.md | sort | uniq | sort -R \
    | while read the_url; do
      echo "Downloading from ${the_url}";
      pod_download_podcast "${the_url}" "${root_directory}";
    done
}

pod_download_podcast() {
  : "${2?"Usage: ${FUNCNAME} URL ROOT_DIRECTORY"}";
  the_url="${1}";
  root_directory="${2}";
  podcast-dl \
    --out-dir "${root_directory}/{{podcast_title}}" \
    --archive "${root_directory}/{{podcast_title}}/archive.json" \
    --episode-template "{{release_date}} {{episode_num}} {{title}}" \
    --threads 2 \
    --include-meta \
    --include-episode-meta \
    --url "${the_url}";
}
```

This has worked wonderfully for a long time. The fateful change was to add these three lines:

```
    --include-episode-transcripts \
    --add-mp3-metadata \
    --always-postprocess \
```

at which point I started encountering errors. Unfortunately, the logs I receive are fairly unreadable (this wasn't a problem before because I simply haven't encountered errors!), but I'll try to run the command with the problematic lines against a known-problematic file.

One podcast that showed problems, though, was True Sunlight: https://feeds.megaphone.fm/BER9965516640

It has an episode entitled "TSP #8 - Exclusive Interview With Mark ‘The Tiger’ Tinsley After Reaching $15+ Million Settlement In Boat Crash Case". This is the episode that showed the problem initially, since that `$1` would get replaced with `` when wrapped with double quotes and used in the `ffmpeg` command.

**Comment by ndouglas** [comment]
Will do! Thank you so much!
